name: Test Release and Manual Triggers

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      release_id:
       description: release version (^^ always run from main)
       default: 9.9.9
       required: true

permissions: read-all

jobs:
  step:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Set release id
        id: setId
        run: |
          echo $GITHUB_EVENT_NAME
          # users are prompted to input with the correct format
          if [[ $GITHUB_EVENT_NAME == "workflow_dispatch" ]]; then
            echo "Workflow dispatch event detected"
            echo "::set-output name=release_id::${{github.event.inputs.release_id}}"
          # release.tag_name has a v prepended. we must remove it.
          else
            echo "release event detected"
            with_v=${{github.event.release.tag_name}}
            without_v=${with_v:1}
            echo "::set-output name=release_id::$without_v"
          fi
          
      - name: Print var
        run: |
          echo ${{github.event.inputs.release_id}}
          echo ${{github.event.release.release_id}}
          echo ${{ steps.setId.outputs.release_id }}